[[LLVM]]
arch = "aarch64"
git-tree-sha1 = "1047b39bd5baab7d41d5904e9776da498d8bef09"
llvm_version = "15"
os = "macos"

    [[LLVM.download]]
    sha256 = "6afe0b086ca3628104abbc26ffacca3c65c98bdb41b4f2a78e48845707e590f1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.aarch64-apple-darwin-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46049ad9eb343f6537e33ee2ec7a1f5c2fb5d283"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "21b2fa57640f1ee51ef0f6217c8ead67aa60f5c07c93ac771b7dffe736f68ee4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b42e1578ecc79225b1e2dccd4d5e51b8c50f644"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "1e9d0cc8de5861bb0daf72147ba71644030b63f4ff438df564753015a1eb70e1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "732166e9f7e61c2cf75e9a9e3f9601eed136f534"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "d49b1ff641cff62f0dbd783e7e253bf4d5a67540c5a0ee5d63ae5cc0b8da8024"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81810fd4e89e014b3f4b340996f7632395c42392"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "78357efaa22d6137540129ff51b30b7a476bd5634c698dba50f58adea740efe3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c91cc7ff3ea4c63709e95492c55e3b364783967"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "c536914f3403a641440e80faef72932c4a1423598709c2f03cde18439032a380"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a42bf379a48129eb28d81b1e1c1240213570e05e"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "31f75bb3669acd240d75ccfaa2ead58dde740f61e6ac118ebb8c83a1f32ce917"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2cd29f1646d0d7b4b7771ce5e5638cf501bc8b5"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "05a79c702bc7abc0ec2948a6548d8a70c5581c362f02c49b0a6a55b37351dfa5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "724a45ddcb6967052842f92ddb73e456565b40b7"
llvm_version = "15"
os = "windows"

    [[LLVM.download]]
    sha256 = "ce34f15e7fc554c51078b773efd0ddf5070ae094cc730227531ec6145a1ac54a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1db78a4149ffdb10260bb04dea17fb413dcbb2ca"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "fb9ea0bce5b722b279ef073bc186e3964dd4deb67b664a713f5170d614410a04"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "6f850541499fd01aa182d00160b8e82cec2d4547"
llvm_version = "15"
os = "macos"

    [[LLVM.download]]
    sha256 = "b0f27f77f2db5c1ce7423c870fbdf9392239ad00cf2aee6396681d76ae05210b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-apple-darwin-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bd30acc4bc37b99ac557ce8b78575880b63aee6"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "d9104fc78ea9f391f3179fbc5887c7abff65eece02b7c7fbda9d5e604b84732f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bd30acc4bc37b99ac557ce8b78575880b63aee6"
libc = "glibc"
llvm_version = "15"
os = "linux"
sanitize = "memory"

    [[LLVM.download]]
    sha256 = "d9104fc78ea9f391f3179fbc5887c7abff65eece02b7c7fbda9d5e604b84732f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af0283ee1a46c14c5136d7caedd492887d2e7c04"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "9ce1b1473ad8b4f92e2facdd53e31f538b867553076828f47c4b4dd0e91361c5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "b5e2305ef38d5ccb1fcd3dd1cd171570388341df"
llvm_version = "15"
os = "freebsd"

    [[LLVM.download]]
    sha256 = "987668d590558c6f38eef9b0fb19a6dfd7dad3d904a0db521ddce71babb1a9da"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a9d171547751995c8468e338471fc7d599c2a9a"
llvm_version = "15"
os = "windows"

    [[LLVM.download]]
    sha256 = "634495ffe249e52cb92a304750760c3f3c68fd58de119c8e7ac9c067407d84e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
git-tree-sha1 = "3f2a1fadabed3852d998d3dc34e61ddb0a5bef86"
llvm_version = "15.asserts"
os = "macos"

    [[LLVM.download]]
    sha256 = "d1bea5dab7fba476b35dcf001860ab2aee7dca1633aee814b1006469419f3a58"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.aarch64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f6b92c2e64ff921a193ec6e2eb548162319a22d"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "062e1368752391c3df4df6daae98ebde9fc2c49239274fd72ce8e2b6abbcf8f8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b9b7c47f6c0c1aebd0c6cf3da317217fa24cc13"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "2580a950b73bd77bde547ec49c712720a1cbddd6c9211bf245770764715b8559"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a55d038f7cab75b37974c0dc31eb8a016c3e0944"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "676e6d5eb5f7bd5cb39a4e6defc0af1de9221fb13f2f60f82ade1f9287b9aed1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d798ab670ebb0ebf2a133ad00c8f6a3b336d65a9"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "8eab9930e506bfd78a22ae44742e2b472d3456dddfdfcc9ce202dbee3eae3ea6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e3e67eabf86317f6724bce5ad8adc7f90c89505"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "89989346a14b3929f865bfb10ada4e077dc049f7a5ad9ea37c18599633d3df89"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2ec595c8c5921984d583f121765246032d667d6"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "e8d6bad0c62cc3b36c974f11bd212d022ada2ea771efd55072292baa22e9bd41"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a02d58ac89acf6e807505b025109692ff65caa1b"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "aa7728c04dd72183d253a31631aa245f6beeb15a2ea68ed6e8c79ac4c03a1bb1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0343adfa12054b30b98cfdb0f48910b87d6377d1"
llvm_version = "15.asserts"
os = "windows"

    [[LLVM.download]]
    sha256 = "a0a01136ba701b8280f18dbd688c305a490f657be764c6fe12e3d7588b60594c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e72950c6ad748c4002b09e921f82a754a2daa35"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "0d5a885cf06e2ec3e4227d13853280c4dec9ef560dfbe18981b0336c94ec7d41"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "0f5b95b54c20f228cc3ceb1d5cdabf39e67e2c05"
llvm_version = "15.asserts"
os = "macos"

    [[LLVM.download]]
    sha256 = "2905b58f8a6be29af72b1b83df17ecc64cc926ea5c7e912c41571260008e929f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d413dea379bfbc00d4459c098f089eb93e65de46"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "caa6910f76cacd10639df9526955a2e898e4b2d358e04d3403ac607452f149e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d413dea379bfbc00d4459c098f089eb93e65de46"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"
sanitize = "memory"

    [[LLVM.download]]
    sha256 = "caa6910f76cacd10639df9526955a2e898e4b2d358e04d3403ac607452f149e0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a4ff1b2ca11b1cb3763f00fe62b01a7e1baccce"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "9acb2870bca77c5ce59dfa4034f35c64b1f54d7d4c1cced719284df3c0fddc6e"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "d3a69289c7e9c7656a34bb03c9b12a84608bd295"
llvm_version = "15.asserts"
os = "freebsd"

    [[LLVM.download]]
    sha256 = "474bee58fffea00dc1702d82aff843d33273c064455d67148509ab0c4902fc85"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34185e73dc9980bd6678c31c3c8c8859cb341a6d"
llvm_version = "15.asserts"
os = "windows"

    [[LLVM.download]]
    sha256 = "ede21007afcfede51bd01a84fb8859bf86638b4703d91a084845821c6ebb4b4f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+12/LLVM.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
