[[LLVM]]
arch = "aarch64"
git-tree-sha1 = "e1c79559c71c14c9f56b8426ae5a31ddd2c6d1b4"
llvm_version = "15"
os = "macos"

    [[LLVM.download]]
    sha256 = "ec7c8aceb9c5cd9c5b1e8f07df752c3ba3fab57e11e6f734d5219b0688e4293f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.aarch64-apple-darwin-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ee23b6bbaaa28194e87f454909a572c1d1fd8e4"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "0d49f9b9282b1517e0fc54269dea58eb7eb54ae917b7d85bc355018ecb7e84ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da9aa3eedadbe42e7eef8be861ec856182cbb551"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "ba6bc0a4fb9487d1a43a311392108ee346f9e3ac3f619f55cf80ca2f427306c8"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62ea4dd410bddb720d4a89bfb512327653a11e97"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "3322c4d8e4330bd038769c786868b367527394b54e15126c9648e61e44e42bdb"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddcda4b749009116ced73629e67563a4608759e4"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "4769a3e9eb5c91796e027e42f18e3e1c16d7e77ff537686a59e1800a2c50e13c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71dc5b4ec6c9719dbe16aa76b2a89f2ad877a28b"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "d387e62f7fd5c22f2ae7fc68ca87063709c1afc84eb974a0f23b458ace58daae"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66d74a1b8ae9e8aa3b5992ae5870f23519dbc80e"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "6ae3c3c16269867b42c14b9bcd9c1be29b6d582bcf07b9da1c50ebc599136f48"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "758ad6eca963ae028c33e94f6a45e640a72ca217"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "798b16a5170ba8f116e8e78adea338feaabf52816bdd5ecc4b59e3eb165120f5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94c58b8c6af63a78d3bbb07823ad5842f04274f9"
llvm_version = "15"
os = "windows"

    [[LLVM.download]]
    sha256 = "e49f41ab16d845ccd98687f3704ceb9a588f96b811ff7c785d90953c40967fe7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32575948a8aa7610ca378bddb6d370807d958ab9"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "9128137a932c2713d3b4fec963feb73dc6641cc5425d5828b47e71066409bfbd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "6b038022e3b2a081e0c89e4e5e88d1a73238992c"
llvm_version = "15"
os = "macos"

    [[LLVM.download]]
    sha256 = "eecf2be4b821c0af5ba142cc73466ec23a84e1b2aab9027388980ddaedbd5fb9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-apple-darwin-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8f4a30e102d5c70e115b795cd0d2a526839455d"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "fd88c10ffcb4a12a8cd99b80fca3ad309094f28d72f1716f4edbaf133c365124"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8f4a30e102d5c70e115b795cd0d2a526839455d"
libc = "glibc"
llvm_version = "15"
os = "linux"
sanitize = "memory"

    [[LLVM.download]]
    sha256 = "fd88c10ffcb4a12a8cd99b80fca3ad309094f28d72f1716f4edbaf133c365124"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "839f94cb2b6221023acc6e8ff43fd693d840092e"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "79b03bceb68e41f4887a73ad2833f7c608b1461538af55c3887a0ad48ff62029"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "45e8a5e085b9ce498e07c7c167cf0bfc9aa07d43"
llvm_version = "15"
os = "freebsd"

    [[LLVM.download]]
    sha256 = "de965c74010e84cbb76386e14b98c53e0cccf722a96ca510236d20eec01f7aa5"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad9f20c607de01ddce00f4ca882f2c0abcc55f02"
llvm_version = "15"
os = "windows"

    [[LLVM.download]]
    sha256 = "a9d748946cbb0c706087ef29a01b170ccf024a5215cb5e59b380deba5dbb1363"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
git-tree-sha1 = "f855fb0f5563dee1876ced6d5fe2de101f6fbf82"
llvm_version = "15.asserts"
os = "macos"

    [[LLVM.download]]
    sha256 = "be32eac7bfdcdea40338259ed6ce4c8a4a04fcb123a078a81758f93aa5570c67"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.aarch64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c82454c3cefa7b43fe652ea66843ee212d44a45"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "6b03ee23b14d269b3269898911b7ba3a144061ee1fd81651977bf303258dcce4"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7c37375ca8c0b87dda76c96eafb985abd72c748"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "c2abad09cfd8bab1ce0e1180a771defe7d9b7b2f2e5830923fd75ad9ac778e8f"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72d8adb4f9eacc667adce5fb3e62c708ad90784f"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "91bcc4b02d8c4db00d974247e73cc5822f28653f7c6fea698fe7cde7b4fab06b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2cd27077ef0eea08db634033242785bae5fb7b5"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "0b0883fa19cc0853e829ca40c0f04ad7fd186306d76263cf77ff0e8a64357750"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4d0c282eba5b54bff1165efeafed3b7da4f77ab"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "4b2baa5db8fe319af21be8175ccfcbadb2883ce44b5fad67065422eb04f32166"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4258986dbb1c8fac70ddcf678ab62f31da348d52"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "374512004b05a0ec53c12414c3263d8e47e120b4a33bfb60ed02d96ece039587"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91abe9453b1581081de314ad91a0dd9a3ec8b2e5"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "d93bc8941114dd991a5150eded341c7d9561696a3d39eab4e2609ef4c80d21fe"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa1118e4a1444c80b407f392c718baf03934ca96"
llvm_version = "15.asserts"
os = "windows"

    [[LLVM.download]]
    sha256 = "d83c6dfbe387cbcde6ff40cb9ca3e0cf1c847fbf28ebd45b97ed2bc8f9561f38"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d14c4b686f63af6a55f44df1b2a114860b75921d"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "c37cb9d24ccda01b5de0bf5538763b230f59e72ed8df84926b7580e21bb6c80c"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "e6180ff9aeb86a1e1f325a8501e8381ad651ce15"
llvm_version = "15.asserts"
os = "macos"

    [[LLVM.download]]
    sha256 = "07cadb7015290c35e49ec0905b0891199f0c0a6c741a62e60d588627e2a69eac"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fb6595898ccf8e36c1076735519893f4e225edc"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "75f727ee84ec9381c4d6c579795292802776326ebbf1c548e0057e6f7e14d736"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fb6595898ccf8e36c1076735519893f4e225edc"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"
sanitize = "memory"

    [[LLVM.download]]
    sha256 = "75f727ee84ec9381c4d6c579795292802776326ebbf1c548e0057e6f7e14d736"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e953e7e69a251783eece8b9ed0b3bba7409331d4"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "14476e6144d56865a380aa5b6969d2cc53dfa9fbed64a5b4c00ee03268691b23"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "a18cecac1e5bccd11dca9903f66a2f5bd6a9af31"
llvm_version = "15.asserts"
os = "freebsd"

    [[LLVM.download]]
    sha256 = "872cf71d220acba308414d5c1a9472904d932d695a7eb759fdcdfa5b7469ac89"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80f1fedb67ff4909a87c7e32f614c4c75f2bed43"
llvm_version = "15.asserts"
os = "windows"

    [[LLVM.download]]
    sha256 = "0d0fa256b4eca57842695cc7f396216951f8478d6105000a911f743903e62247"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+13/LLVM.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
